raw_data_csv_path: artifacts/security_alignment/raw_data.csv
directory: artifacts/security_alignment/
models:
  - name: starcoder7b
    output_dir: artifacts/security_alignment/starcoder7b_results
    model: bigcode/starcoder2-7b

  - name: starcoder3b
    output_dir: artifacts/security_alignment/starcoder3b_results
    model: bigcode/starcoder2-3b

  - name: mellum
    output_dir: artifacts/security_alignment/mellum_results
    model: JetBrains/Mellum-4b-base

  - name: deepseek
    output_dir: artifacts/security_alignment/deepseek_results
    model: deepseek-ai/deepseek-coder-6.7b-base

  - name: codellama7b
    output_dir: artifacts/security_alignment/codellama7b_results
    model: meta-llama/CodeLlama-7b-hf

  - name: codellama13b
    output_dir: artifacts/security_alignment/codellama13b_results
    model: meta-llama/CodeLlama-13b-hf
